// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8jRhOUQB7p7BuhQ8wePMWt_gAZngJSTc',
    appId: '1:481197829809:web:3bcc0c5cb690d63e19bc90',
    messagingSenderId: '481197829809',
    projectId: 'flutter-cookbook-c7b43',
    authDomain: 'flutter-cookbook-c7b43.firebaseapp.com',
    storageBucket: 'flutter-cookbook-c7b43.appspot.com',
    measurementId: 'G-BS6SYXPSRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VnJ3JmoaPCKgrwFO0pcxxtuDVDz0Jtw',
    appId: '1:481197829809:android:bba4c93dc248c44719bc90',
    messagingSenderId: '481197829809',
    projectId: 'flutter-cookbook-c7b43',
    storageBucket: 'flutter-cookbook-c7b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2GG6NS9JRs1uq1WGvNQ5bfuIa-B3aNc',
    appId: '1:481197829809:ios:b51a0f228a8183d119bc90',
    messagingSenderId: '481197829809',
    projectId: 'flutter-cookbook-c7b43',
    storageBucket: 'flutter-cookbook-c7b43.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs2GG6NS9JRs1uq1WGvNQ5bfuIa-B3aNc',
    appId: '1:481197829809:ios:5e887d0e83b9d5c219bc90',
    messagingSenderId: '481197829809',
    projectId: 'flutter-cookbook-c7b43',
    storageBucket: 'flutter-cookbook-c7b43.appspot.com',
    iosBundleId: 'com.example.signup.RunnerTests',
  );
}
